deploy: build
    wrangler pages deploy \
        --commit-dirty=true \
        --project-name=chilly \
        --branch=main public

build:
    hugo

dev:
    hugo serve

font:
    # https://virgil.excalidraw.com/
    wget -P static/ https://virgil.excalidraw.com/Virgil.woff2
