apiVersion: v1
kind: Pod
metadata:
  name: iperf
  labels:
    # https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
    app.kubernetes.io/name: iperf
spec:
  containers:
  - name: iperf
    image: docker.io/griffinhtdocker/iperf
    ports:
    - containerPort: 5201
      name: iperf
    command: 
    - iperf3
    - --server
---
apiVersion: v1
kind: Service
metadata:
  name: iperf
spec:
  selector:
    app.kubernetes.io/name: iperf
  type: LoadBalancer
  ports:
  - port: 5201
    targetPort: iperf
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: iperf
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: iperf
