credentials:
    gcloud container clusters get-credentials --location=us-east1 public

# make sure networking works idk
# basically this command should fail
# there should really be a better way to do this tho
test:
    kubectl exec -it searxng -- sh -c "wget -qO- --timeout=2 redlib > /dev/null"

# #!/usr/bin/env bash
#set -o pipefail
#ls caddy/*.json | xargs -P 16 -I {} sh -c 'jsonnet {} -V configMap=caddy-v10 | kubectl apply --warnings-as-errors -f -'

deploy:
    # todo improve concurrency somehow?
    #https://stackoverflow.com/questions/28357997/running-programs-in-parallel-using-xargs

    jsonnet public.json | KUBECTL_APPLYSET=true kubectl apply --warnings-as-errors -f - --prune --applyset=test --namespace=default
    #jsonnet public.json | kubectl delete --warnings-as-errors -f - --namespace=default
