# file is unused
default file:
    clear
    jsonnet kubernetes.json | kubectl diff -f -

credentials:
    gcloud container clusters get-credentials --location=us-east1 public

# make sure networking works idk
# basically this command should fail
# there should really be a better way to do this tho
test:
    kubectl exec -it searxng -- sh -c "wget -qO- --timeout=2 redlib > /dev/null"

deploy:
    #!/usr/bin/env bash
    set -o pipefail
    # todo improve concurrency somehow?
    #https://stackoverflow.com/questions/28357997/running-programs-in-parallel-using-xargs

    ls caddy/*.json | xargs -P 16 -I {} sh -c 'jsonnet {} -V configMap=caddy-v10 | kubectl apply --warnings-as-errors -f -'
    jsonnet kubernetes.json | kubectl apply --warnings-as-errors -f -
