apiVersion: v1
kind: Deployment
metadata:
  name: miniflux
  labels:
    app.kubernetes.io/name: miniflux
spec:
  containers:
  - name: miniflux
    image: quay.io/redlib/redlib:latest
    ports:
      - containerPort: 8080
        name: http
---
apiVersion: v1
kind: Service
metadata:
  name: redlib
spec:
  selector:
    app.kubernetes.io/name: redlib
      #type: default clusterip
  ports:
    - port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redlib
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redlib
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: caddy
apiVersion: v1
kind: Pod
metadata:
  name: miniflux
  labels:
    app.kubernetes.io/name: miniflux
spec:
  containers:
  - name: miniflux
    image: docker.io/miniflux/miniflux:latest
    ports:
      - containerPort: 8080
        name: http
    env:
      - name: DATABASE_URL
        value: postgres://postgres@postgres/miniflux?sslmode=disable
      - name: AUTH_PROXY_HEADER
        value: X-Forwarded-User 
      - name: AUTH_PROXY_USER_CREATION
        value: true
        #- METRICS_COLLECTOR=1
        #- 'METRICS_ALLOWED_NETWORKS=0.0.0.0/0,::/0'
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux
spec:
  selector:
    app.kubernetes.io/name: miniflux
      #type: default clusterip
  ports:
    - port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: miniflux
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: miniflux
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: caddy
